### ISSUE TITLE
Old Github URL in manifest.json

### ISSUE THREAD

**Issue by matthijskooijman** [wakeuteu/socksproxy-firefox-addon#8]
Inside Firefox, with this extension installed, I go to Tools -> Addons and themes, then click this extension and it shows:

![image](https://user-images.githubusercontent.com/194491/158367554-b00c95c7-2f99-4a01-9a67-690b3d08c565.png)

Note the old URL at the bottom. It seems like the url in manifest.json is incorrect (but I could have sworn when I first checked it in the github repo today, it was correct, but it seems to be wrong): https://github.com/wakeuteu/socksproxy-firefox-addon/blob/0a8f98e1b23171ac43fa215101b6fa6a48c38d87/manifest.json#L7

Interestingly enough https://addons.mozilla.org/en-US/firefox/addon/socksproxy/ *does* list the right github URL under homepage...

On a related note, it seems that addons.mozilla.org still has the 1.0.0 version, while git has 1.0.1:

![image](https://user-images.githubusercontent.com/194491/158369754-2436edd8-88ac-44f6-8c06-340d146216c8.png)

(I originally thought this explained the incorrect URL, but it seems it is still incorrect in 1.0.1)

**Comment by wakeuteu** [comment]
Hi,
Thanks for the feedback, I actually left this repo alone for a while. I'm fixing this is in commit b73b43d8bdc4a00ca0fb75e9b0ddd10b47aa41c6. (v1.1.0). I will make sure to publish the latest release to the addons center.
